---
title: "Enlaces Ciencia de Datos"
author: "Ricardo Alberich"
date: "31/1/2020"
output:
  pdf_document: default
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Enlaces a Material propio

## Manuales de R básicos

1. [AprendeR1](https://aprender-uib.github.io/AprendeR1/). Manual de R parte 1. Descriptiva.
2. [AprendeR2](https://aprender-uib.github.io/AprendeR2/).  Manual de R parte 2. Inferencial.

## Material cursos probabilidad y estadística básicos

1. [Probabilidad y variables aleatorias para ML con R y Python](https://joanby.github.io/bookdown-probabilidad)
    + [Presentaciones](https://github.com/joanby/probabilidad)
    + [Shiny](https://joanby.shinyapps.io/DistribucionesNotables/)

2. [Curso completo de estadística inferencial con R y Python](https://github.com/joanby/estadistica-inferencial)
    + [Sinhy intervalos de confianza y contraste hipótesis](https://joanby.shinyapps.io/contrastes-hipotesis/)



## Cursos en linea de Probabilidad, Estadística y  Machine Learning.


### Cursos

1. [Curso completo de Estadística descriptiva - RStudio y Python ](https://www.udemy.com/course/estadistica-descriptiva/)
2. [Machine Learning de A a la Z: R y Python para Data Science ](https://www.udemy.com/course/machinelearning-es/)
3. [Curso completo de Machine Learning: Data Science con RStudio](https://www.udemy.com/course/r-data-science/)
4. [Probabilidad para Machine Learning y Big Data con R y Python](https://www.udemy.com/course/probabilidad-y-variables-aleatorias-para-ml-con-r-y-python/)
5. [Probabilidad para Machine Learning y Big Data con R y Python](https://www.udemy.com/course/estadisticainferencial/)

**Material  gratis de los tres primeros cursos.**

1. (https://github.com/joanby/r-basic)
2. (https://github.com/joanby/machinelearning-az)
3. (https://github.com/joanby/r-course)


### Itinerarios

[Página de itinerarios](https://frogames.es/rutas-de-aprendizaje/)

## Libros del entorno de R y Rstudio

En general los libros gratuitos de (https://bookdown.org/)

Dos básico que introducen a las librerías tidyverse son 

1. [R for Data Science](https://r4ds.had.co.nz/)
2. [Tidy text](https://www.tidytextmining.com/)

